### Register Patient
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "email": "patient1@test.com",
  "password": "123456",
  "role": "patient",
  "fullName": "John Doe",
  "dob": "1955-05-10",
  "gender": "Male",
  "emergencyContact": "9999999999"
}

###

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "patient1@test.com",
  "password": "123456"
}

###

### Protected Route Test
GET http://localhost:5000/api/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTZmMjY1NTAyNzIxZWQwNTJjMTY2MiIsInJvbGUiOiJwYXRpZW50IiwiaWF0IjoxNzcxNTAwMzAxLCJleHAiOjE3NzIxMDUxMDF9.oMfOoE5U_LP6Js9cNrSdcN3IfNBCsQWZquQddPlJ64E

###

### Get My Patient Profile
GET http://localhost:5000/api/patient/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTZmMjY1NTAyNzIxZWQwNTJjMTY2MiIsInJvbGUiOiJwYXRpZW50IiwiaWF0IjoxNzcxNTAwMzAxLCJleHAiOjE3NzIxMDUxMDF9.oMfOoE5U_LP6Js9cNrSdcN3IfNBCsQWZquQddPlJ64E

